import headingImg from "./EEA.png"
import twinRider from "./Twin-Riders.png"
import sliderImg from "./ADULT-DOUBLE-01.png"
import desertImg from "./desert_ex.jpg"
import singleImg from "./Single-Riders.png"
import adventureImg from "./Adventure-TRNS.png"
import desertEx from "./desert_ex.jpg"
import galleryImg from "./gallery_m1.jpg"
import whiteBg from "./white_bg_02.jpg"
export {headingImg, twinRider, sliderImg, desertImg, singleImg, adventureImg, desertEx, galleryImg,whiteBg }