import headingImg from "./EEA.png"
import twinRider from "./Twin-Riders.png"
import sliderImg from "./ADULT-DOUBLE-01.png"
import desertImg from "./desert_ex.jpg"
import singleImg from "./Single-Riders.png"
import adventureImg from "./Adventure-TRNS.png"
import desertEx from "./desert_ex.jpg"
import galleryImg from "./gallery_m1.jpg"
import whiteBg from "./white_bg_02.jpg"
import logo from "./logo_images.png"
import sharma320 from "./SHARMAX-hummer-320-CC.png"
import sharma180 from "./SHARMAX-ATV-CROSS-180-CC.png"
import kymko250 from "./kymko-mxu-250-cc.png"
import polaris1000 from "./POLARIS-RZR-1000-CC.png"
import sharmaATV250 from "./SHARMAX-ATV-CROSS-180-CC.png"
import bluebuggy from "./ADULT-DOUBLE-03.png"
import sharmaatv250 from "./SHARMAX-ATV-250-CC.png"
import cannam1000 from "./cannam.png"
import cannam4 from "./cannam4.png"
import road1 from "./1.webp"
import bike from "./bike.webp"
import road2 from "./other_3.webp"
import great from "./greate_deal.png"
import half from "./half_celcal.png"
import last from "./last.jpg"
import user from "./user.jpg"
import desert from "./desertxtrem_1.png"
import desert1 from "./desert1.jpg"
import desert2 from "./desert2.jpg"
import desert3 from "./desert3.png"
import desert4 from "./desert4.png"
import desert5 from "./desert5.jpg"
import favorite from "./favorute1.jpg"
import favorite1 from "./favorate2.jpg"
import favorite2 from "./favorate3.png"


export {favorite,favorite1,favorite2, desert,desert1,desert2,desert3,desert4,desert5,headingImg,last,sharma320,user, road1,half ,great ,bike, road2, cannam1000, cannam4,sharma180,kymko250 , bluebuggy ,polaris1000,sharmaATV250,sharmaatv250 ,twinRider, sliderImg, desertImg, singleImg, adventureImg, desertEx,logo, galleryImg,whiteBg, }